[package]
name = "graph-generators"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "MIT"
repository = "https://github.com/mneumann/graph-generators-rs"
description = "Graph generator algorithms"
keywords = ["graph", "algorithm"]

[dependencies]
rand = "0.3"
